#!/usr/bin/env npx tsx
/**
 * codegen-pages.ts — Phase F preview generator.
 *
 * Pure function of:
 *   - archive/wordpress/scrape/route-map.json   (route source + new paths + types)
 *   - Supabase page_content table               (actual seeded field_keys per page)
 *
 * Writes generated page.tsx files to site/.codegen-preview/ — DOES NOT touch
 * site/src/app/(site)/. Also writes site/.codegen-preview/MANIFEST.json.
 *
 * Run:  npm run codegen:pages
 */

import { readFile, writeFile, mkdir, rm, stat } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { config as loadEnv } from 'dotenv';
import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import { templateRegistry, type TemplateRef } from '../src/components/templates/registry';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const SITE_DIR = resolve(__dirname, '..');
const REPO_DIR = resolve(SITE_DIR, '..');

loadEnv({ path: join(SITE_DIR, '.env.local') });

const ROUTE_MAP_PATH = join(REPO_DIR, 'archive/wordpress/scrape/route-map.json');
// Codegen writes directly into the live (site) tree. Files that don't start
// with the GENERATED marker are preserved (hand-edited surfaces).
const OUT_DIR = join(SITE_DIR, 'src/app/(site)');
const MANIFEST_PATH = join(SITE_DIR, '.codegen-manifest.json');
const GENERATED_MARKER = '// GENERATED by scripts/codegen-pages.ts';

// ── Types ──

type RouteItem = {
  oldPath: string;
  oldSlug: string;
  newPath: string;
  type: string;
  key: string;
  scrapeFile: string;
  aliases: string[];
};

type RouteMap = { generatedAt: string; count: number; items: RouteItem[] };

type ContentField = { field_key: string; value_type: string; value: string };

// Fields that exist in the DB (so admin can edit, generateMetadata can read)
// but should NEVER render as visible elements in the page body.
const BODY_SKIP_KEYS = new Set<string>([
  'slug',
  'date_published',
  'excerpt',
  'body_html',           // full HTML blob — duplicates h1/h2/p decomposition
  'meta.title',          // lives in <head> via generateMetadata
  'meta.description',    // <head>
  'meta.og_image',       // <head>
]);

// Mechanical (decomposed) prefixes — heading hierarchy that should be preferred
// over a heading key losing to a non-mechanical equivalent only when no semantic
// option is available.
const MECHANICAL_PREFIXES = new Set<string>([
  'h1', 'h2', 'h3', 'h4', 'h5', 'h6',
  'p', 'list', 'quote', 'block', 'image', 'form',
]);

function priorityRank(fieldKey: string): number {
  const prefix = fieldKey.split('.')[0];
  // 1 = semantic (dotted, non-mechanical prefix)  ← e.g. "pray.title"
  if (fieldKey.includes('.') && !MECHANICAL_PREFIXES.has(prefix)) return 1;
  // 2 = heading mechanical
  if (/^h[1-6]\./.test(fieldKey)) return 2;
  // 3 = anything else
  return 3;
}

type ManifestEntry = {
  key: string;
  type: string;
  newPath: string;
  outFile: string;
  fieldKeyCount: number;
  componentCounts: {
    EditableContent: number;
    EditableRichText: number;
    EditableImage: number;
  };
  warnings: string[];
};

// ── Helpers ──

function pascalCase(s: string): string {
  return s
    .replace(/[^a-zA-Z0-9]+/g, ' ')
    .split(' ')
    .filter(Boolean)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join('');
}

function outputPathFor(item: RouteItem): string {
  // Path is RELATIVE to OUT_DIR (which is src/app/(site)). The (site) route
  // group prefix is supplied by OUT_DIR — do NOT prepend it here, otherwise
  // files land at src/app/(site)/(site)/...
  if (item.type === 'index_filter') {
    // Filter routes share the index's base path with a query string in newPath.
    // Each filter becomes a unique synthetic route under (site) using its
    // oldPath. Phase H will collapse these into ?query= params on the parent.
    const segs = item.oldPath.split('/').filter(Boolean);
    return join(...segs, 'page.tsx');
  }
  const path = item.newPath.split('?')[0];
  if (path === '/' || path === '') return 'page.tsx';
  const segs = path.split('/').filter(Boolean);
  return join(...segs, 'page.tsx');
}

function asTagFor(fieldKey: string): string {
  if (fieldKey.startsWith('h1.')) return 'h1';
  if (fieldKey.startsWith('h2.')) return 'h2';
  if (fieldKey.startsWith('h3.')) return 'h3';
  if (fieldKey.startsWith('h4.')) return 'h4';
  if (fieldKey.startsWith('h5.')) return 'h5';
  if (fieldKey.startsWith('h6.')) return 'h6';
  if (fieldKey.startsWith('meta.')) return 'span';
  if (fieldKey.startsWith('form.label.')) return 'label';
  if (fieldKey === 'form.button' || fieldKey.startsWith('form.button.')) return 'span';
  return 'span';
}

function groupKey(fieldKey: string): string {
  if (/^h[1-6]\./.test(fieldKey)) return 'h' + fieldKey.charAt(1);
  if (fieldKey.startsWith('p.')) return 'p';
  if (fieldKey.startsWith('list.')) return 'list';
  if (fieldKey.startsWith('quote.')) return 'quote';
  if (fieldKey.startsWith('block.')) return 'block';
  if (fieldKey.startsWith('image.')) return 'image';
  if (fieldKey.startsWith('form.')) return 'form';
  if (fieldKey.startsWith('meta.')) return 'meta';
  return 'other';
}

// Section render order
const GROUP_ORDER = ['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'p', 'list', 'quote', 'block', 'image', 'form', 'other'];

// ── Supabase ──

function getSupabase(): SupabaseClient {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL ?? process.env.SUPABASE_URL;
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY;
  if (!url || !key) {
    console.error('Missing NEXT_PUBLIC_SUPABASE_URL/SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY in site/.env.local');
    process.exit(1);
  }
  return createClient(url, key, { auth: { autoRefreshToken: false, persistSession: false } });
}

async function fetchFields(sb: SupabaseClient, pageKey: string): Promise<ContentField[]> {
  const { data, error } = await sb
    .from('page_content')
    .select('field_key, value_type, value')
    .eq('page_key', pageKey)
    .order('field_key', { ascending: true });
  if (error) {
    console.error(`[supabase] fetch fields for "${pageKey}":`, error.message);
    return [];
  }
  return (data ?? []) as ContentField[];
}

type DedupeReportEntry = { pageKey: string; collapsed: number; details: Array<{ kept: string; dropped: string[]; sample: string }> };
const dedupeReport: DedupeReportEntry[] = [];

/**
 * Lower-case + collapse smart-quotes, em/en-dashes, and whitespace so that
 * cosmetic punctuation differences don't prevent deduplication. The displayed
 * value remains the original — this is comparison-only.
 */
function normalizeForDedupe(v: string): string {
  return v
    .toLowerCase()
    .replace(/[‘’]/g, "'")     // smart single quotes → '
    .replace(/[“”]/g, '"')     // smart double quotes → "
    .replace(/[–—]/g, '-')     // en-dash, em-dash → -
    .replace(/\s+/g, ' ')                 // collapse all whitespace
    .trim();
}

/**
 * Collapse fields that share the same value (under normalized comparison).
 * Returns the surviving subset (preserving the original sort order) plus
 * the per-page collapse details.
 *
 * Priority: lower priorityRank wins. Tie-breaker: original (alphabetical) order.
 */
function dedupeByValue(pageKey: string, fields: ContentField[]): ContentField[] {
  const orderIndex = new Map<string, number>();
  fields.forEach((f, i) => orderIndex.set(f.field_key, i));

  // Group keys by NORMALIZED value (cosmetic punctuation/whitespace ignored).
  const byNormalized = new Map<string, ContentField[]>();
  for (const f of fields) {
    const orig = (f.value ?? '').trim();
    if (!orig) continue;
    const norm = normalizeForDedupe(orig);
    if (!byNormalized.has(norm)) byNormalized.set(norm, []);
    byNormalized.get(norm)!.push(f);
  }

  const winners = new Set<string>(); // field_keys to keep
  const losersByWinner = new Map<string, string[]>();
  const winnerSample = new Map<string, string>();

  for (const f of fields) {
    if ((f.value ?? '').trim() === '') {
      winners.add(f.field_key); // empties are never collapsed
    }
  }

  for (const [, group] of byNormalized) {
    if (group.length === 1) {
      winners.add(group[0].field_key);
      continue;
    }
    // Sort by priority then by original order
    const sorted = [...group].sort((a, b) => {
      const pa = priorityRank(a.field_key);
      const pb = priorityRank(b.field_key);
      if (pa !== pb) return pa - pb;
      return (orderIndex.get(a.field_key) ?? 0) - (orderIndex.get(b.field_key) ?? 0);
    });
    const kept = sorted[0];
    winners.add(kept.field_key);
    const dropped = sorted.slice(1).map((f) => f.field_key);
    losersByWinner.set(kept.field_key, dropped);
    // Sample uses the *original* (non-normalized) value of the surviving row.
    const display = (kept.value ?? '').trim();
    winnerSample.set(kept.field_key, display.length > 80 ? display.slice(0, 77) + '…' : display);
  }

  if (losersByWinner.size > 0) {
    const collapsed = [...losersByWinner.values()].reduce((n, ds) => n + ds.length, 0);
    dedupeReport.push({
      pageKey,
      collapsed,
      details: [...losersByWinner.entries()].map(([kept, dropped]) => ({
        kept,
        dropped,
        sample: winnerSample.get(kept) ?? '',
      })),
    });
  }

  return fields.filter((f) => winners.has(f.field_key));
}

// ── Page emit ──

function pickTemplate(item: RouteItem): TemplateRef | null {
  return (
    templateRegistry.byKey[item.key] ??
    templateRegistry.byType[item.type] ??
    templateRegistry.fallback ??
    null
  );
}

function pickRedirect(item: RouteItem): string | null {
  return templateRegistry.redirectKeys?.[item.key] ?? null;
}

function emitRedirectShim(destUrl: string): { code: string; counts: ManifestEntry['componentCounts'] } {
  const counts = { EditableContent: 0, EditableRichText: 0, EditableImage: 0 };
  const code = `// GENERATED by scripts/codegen-pages.ts — do not hand-edit
import { redirect } from "next/navigation";

export default function Page() {
  redirect(${JSON.stringify(destUrl)});
}
`;
  return { code, counts };
}

function emitTemplateShim(item: RouteItem, tpl: TemplateRef): { code: string; counts: ManifestEntry['componentCounts'] } {
  const componentName = pascalCase(item.key) + 'Page';
  // Shim wires both providers so the template can use Editable* freely. We
  // count the template render itself as a single EditableContent slot for the
  // manifest's component totals — accurate per-component counts live in the
  // template file itself.
  const counts = { EditableContent: 1, EditableRichText: 0, EditableImage: 0 };
  const code = `// GENERATED by scripts/codegen-pages.ts — do not hand-edit
import type { Metadata } from "next";
import { fetchPageContent, fetchAssets } from "@/lib/content";
import { ContentProviderWrapper } from "@/components/ContentProviderWrapper";
import { AssetProviderWrapper } from "@/components/AssetProviderWrapper";
import { ${tpl.exportName} } from "${tpl.importPath}";

const PAGE_KEY = "${item.key}";

export async function generateMetadata(): Promise<Metadata> {
  const [page, global] = await Promise.all([
    fetchPageContent(PAGE_KEY),
    fetchPageContent("global"),
  ]);
  const title = page.get("meta.title")?.value ?? global.get("meta.title")?.value ?? "";
  const description = page.get("meta.description")?.value ?? global.get("meta.description")?.value ?? "";
  return { title, description };
}

export default async function ${componentName}() {
  const [content, assets] = await Promise.all([
    fetchPageContent(PAGE_KEY),
    fetchAssets(PAGE_KEY + "."),
  ]);
  const contentEntries = Array.from(content.values());
  const assetEntries = Array.from(assets.values());
  return (
    <ContentProviderWrapper pageKey={PAGE_KEY} entries={contentEntries}>
      <AssetProviderWrapper entries={assetEntries}>
        <${tpl.exportName} pageKey={PAGE_KEY} />
      </AssetProviderWrapper>
    </ContentProviderWrapper>
  );
}
`;
  return { code, counts };
}

function emitIndexFilterStub(item: RouteItem): { code: string; counts: ManifestEntry['componentCounts'] } {
  const componentName = pascalCase(item.key) + 'Page';
  const counts = { EditableContent: 1, EditableRichText: 0, EditableImage: 0 };
  const code = `// GENERATED by scripts/codegen-pages.ts — do not hand-edit
import type { Metadata } from "next";
import { fetchPageContent } from "@/lib/content";
import { ContentProviderWrapper } from "@/components/ContentProviderWrapper";
import { EditableContent } from "@/components/EditableContent";

const PAGE_KEY = "${item.key}";

export async function generateMetadata(): Promise<Metadata> {
  const [page, global] = await Promise.all([
    fetchPageContent(PAGE_KEY),
    fetchPageContent("global"),
  ]);
  const title = page.get("meta.title")?.value ?? global.get("meta.title")?.value ?? "";
  const description = page.get("meta.description")?.value ?? global.get("meta.description")?.value ?? "";
  return { title, description };
}

export default async function ${componentName}() {
  const content = await fetchPageContent(PAGE_KEY);
  const contentEntries = Array.from(content.values());
  return (
    <ContentProviderWrapper pageKey={PAGE_KEY} entries={contentEntries}>
      <section data-group="h1">
        <EditableContent fieldKey="meta.title" as="h1" />
      </section>
      <section data-group="filter-stub">
        <p>Filtered list — wiring in Phase H.</p>
      </section>
    </ContentProviderWrapper>
  );
}
`;
  return { code, counts };
}

function emitNormalPage(
  item: RouteItem,
  fieldsRaw: ContentField[],
): { code: string; counts: ManifestEntry['componentCounts']; warnings: string[] } {
  const componentName = pascalCase(item.key) + 'Page';
  const warnings: string[] = [];
  const counts = { EditableContent: 0, EditableRichText: 0, EditableImage: 0 };

  // Drop fields that should never render in body (admin still edits them, head still reads them).
  const afterSkip = fieldsRaw.filter((f) => !BODY_SKIP_KEYS.has(f.field_key));

  // Collapse same-value duplicates within this page.
  const fields = dedupeByValue(item.key, afterSkip);

  // Group fields
  const groups = new Map<string, ContentField[]>();
  for (const f of fields) {
    const g = groupKey(f.field_key);
    if (!groups.has(g)) groups.set(g, []);
    groups.get(g)!.push(f);
  }

  // Build a set of image url keys for which we already emit an EditableImage,
  // so we can skip the matching .alt key when iterating.
  const imageUrlKeys = new Set<string>();
  const skipKeysInBody = new Set<string>();
  for (const f of fields) {
    if (f.value_type === 'url' && /^image\.\d+\.url$/.test(f.field_key)) {
      imageUrlKeys.add(f.field_key);
      const altKey = f.field_key.replace(/\.url$/, '.alt');
      skipKeysInBody.add(altKey);
    }
  }

  // Imports (set conditionally)
  let usesEditableContent = false;
  let usesEditableRichText = false;
  let usesEditableImage = false;

  // Decide if we need fetchAssets/AssetProvider
  const hasImageKeys = (groups.get('image') ?? []).some((f) =>
    /^image\.\d+\.(url|alt)$/.test(f.field_key) || /^image\.\d+$/.test(f.field_key),
  );

  // Build sections in order
  const sectionLines: string[] = [];
  for (const g of GROUP_ORDER) {
    const fs = groups.get(g);
    if (!fs || fs.length === 0) continue;
    if (g === 'meta') continue; // head only

    const lines: string[] = [];
    if (g === 'image') {
      // Render one EditableImage per image.NN group (using the url key).
      const seen = new Set<string>();
      for (const f of fs) {
        const m = /^image\.(\d+)\.(url|alt)$/.exec(f.field_key) ?? /^image\.(\d+)$/.exec(f.field_key);
        if (!m) {
          // Unrecognized image key shape — emit as text fallthrough.
          lines.push(`        <EditableContent fieldKey="${f.field_key}" as="${asTagFor(f.field_key)}" />`);
          usesEditableContent = true;
          counts.EditableContent++;
          continue;
        }
        const idx = m[1];
        if (seen.has(idx)) continue;
        seen.add(idx);
        // Prefer the .url-suffixed key when present, else the bare image.NN key.
        const urlKey = imageUrlKeys.has(`image.${idx}.url`) ? `image.${idx}.url` : `image.${idx}`;
        lines.push(`        <EditableImage fieldKey="${urlKey}" />`);
        usesEditableImage = true;
        counts.EditableImage++;
      }
    } else {
      for (const f of fs) {
        if (skipKeysInBody.has(f.field_key)) continue;
        if (f.field_key.startsWith('seo.')) continue;
        if (f.value_type === 'meta') continue;

        const tag = asTagFor(f.field_key);

        if (f.value_type === 'html' || f.value_type === 'richtext' || f.value_type === 'markdown') {
          lines.push(`        <EditableRichText fieldKey="${f.field_key}" />`);
          usesEditableRichText = true;
          counts.EditableRichText++;
        } else if (f.value_type === 'datetime' || f.value_type === 'date') {
          lines.push(`        <EditableContent fieldKey="${f.field_key}" as="time" />`);
          usesEditableContent = true;
          counts.EditableContent++;
        } else if (f.value_type === 'url' && f.field_key.startsWith('image.')) {
          // Stray image url that didn't match shape — render as text link target.
          lines.push(`        <EditableContent fieldKey="${f.field_key}" as="span" />`);
          usesEditableContent = true;
          counts.EditableContent++;
        } else {
          lines.push(`        <EditableContent fieldKey="${f.field_key}" as="${tag}" />`);
          usesEditableContent = true;
          counts.EditableContent++;
        }
      }
    }

    if (lines.length === 0) continue;
    sectionLines.push(`      <section data-group="${g}">`);
    sectionLines.push(...lines);
    sectionLines.push(`      </section>`);
  }

  // Index types get a list-children placeholder
  if (item.type === 'index') {
    sectionLines.push(`      <section data-group="list-placeholder">`);
    sectionLines.push(`        {/* TODO Phase H: <ListSection /> for child query */}`);
    sectionLines.push(`      </section>`);
  }

  // Warnings
  const bodyFieldCount = fields.filter(
    (f) => !f.field_key.startsWith('meta.') && !f.field_key.startsWith('seo.'),
  ).length;
  if (bodyFieldCount === 0 && item.type !== 'index_filter') {
    warnings.push('zero body field_keys (only meta.*)');
  }
  if (!hasImageKeys && ['team', 'sermon', 'blog'].includes(item.type)) {
    warnings.push(`no image.* keys but type=${item.type} (probably needs hero image)`);
  }

  // Imports
  const imports: string[] = [
    '// GENERATED by scripts/codegen-pages.ts — do not hand-edit',
    'import type { Metadata } from "next";',
  ];
  if (hasImageKeys) {
    imports.push('import { fetchPageContent, fetchAssets } from "@/lib/content";');
  } else {
    imports.push('import { fetchPageContent } from "@/lib/content";');
  }
  imports.push('import { ContentProviderWrapper } from "@/components/ContentProviderWrapper";');
  if (hasImageKeys) {
    imports.push('import { AssetProviderWrapper } from "@/components/AssetProviderWrapper";');
  }
  if (usesEditableContent) imports.push('import { EditableContent } from "@/components/EditableContent";');
  if (usesEditableRichText) imports.push('import { EditableRichText } from "@/components/EditableRichText";');
  if (usesEditableImage) imports.push('import { EditableImage } from "@/components/EditableImage";');

  // Default body fallback if no sections were emitted
  if (sectionLines.length === 0) {
    sectionLines.push(`      <section data-group="empty">`);
    sectionLines.push(`        {/* No body field_keys for this page yet. Add rows in admin to populate. */}`);
    sectionLines.push(`      </section>`);
  }

  const dataFetch = hasImageKeys
    ? `  const [content, assets] = await Promise.all([
    fetchPageContent(PAGE_KEY),
    fetchAssets(PAGE_KEY + "."),
  ]);
  const contentEntries = Array.from(content.values());
  const assetEntries = Array.from(assets.values());`
    : `  const content = await fetchPageContent(PAGE_KEY);
  const contentEntries = Array.from(content.values());`;

  const wrapOpen = hasImageKeys
    ? `    <ContentProviderWrapper pageKey={PAGE_KEY} entries={contentEntries}>
      <AssetProviderWrapper entries={assetEntries}>`
    : `    <ContentProviderWrapper pageKey={PAGE_KEY} entries={contentEntries}>`;

  const wrapClose = hasImageKeys
    ? `      </AssetProviderWrapper>
    </ContentProviderWrapper>`
    : `    </ContentProviderWrapper>`;

  // Indent each section line one extra level if AssetProviderWrapper is nested
  const renderedSections = hasImageKeys
    ? sectionLines.map((l) => '  ' + l).join('\n')
    : sectionLines.join('\n');

  const code = `${imports.join('\n')}

const PAGE_KEY = "${item.key}";

export async function generateMetadata(): Promise<Metadata> {
  const [page, global] = await Promise.all([
    fetchPageContent(PAGE_KEY),
    fetchPageContent("global"),
  ]);
  const title = page.get("meta.title")?.value ?? global.get("meta.title")?.value ?? "";
  const description = page.get("meta.description")?.value ?? global.get("meta.description")?.value ?? "";
  return { title, description };
}

export default async function ${componentName}() {
${dataFetch}
  return (
${wrapOpen}
${renderedSections}
${wrapClose}
  );
}
`;

  return { code, counts, warnings };
}

// ── Main ──

async function main() {
  console.log('codegen-pages: starting (preview only — writes to site/.codegen-preview/)\n');

  const routeMap = JSON.parse(await readFile(ROUTE_MAP_PATH, 'utf8')) as RouteMap;
  console.log(`Loaded route-map: ${routeMap.count} items\n`);

  const sb = getSupabase();

  await mkdir(OUT_DIR, { recursive: true });

  const manifest: ManifestEntry[] = [];
  const outFileToKeys = new Map<string, string[]>();
  const skippedHandEdited: string[] = [];

  for (const item of routeMap.items) {
    const outRel = outputPathFor(item);
    const outAbs = join(OUT_DIR, outRel);

    // Track collisions
    if (!outFileToKeys.has(outRel)) outFileToKeys.set(outRel, []);
    outFileToKeys.get(outRel)!.push(item.key);

    let code: string;
    let counts: ManifestEntry['componentCounts'];
    let warnings: string[] = [];
    let fieldKeyCount = 0;

    const redirectTo = pickRedirect(item);
    const tpl = pickTemplate(item);

    if (redirectTo) {
      // Redirect shim wins over template/per-key dump. Used for de-duplicated
      // routes (e.g., team.bishopwilson → /team/bishop-huel-wilson).
      const r = emitRedirectShim(redirectTo);
      code = r.code;
      counts = r.counts;
      fieldKeyCount = 0;
    } else if (tpl) {
      // Registered template wins over per-key dump.
      const r = emitTemplateShim(item, tpl);
      code = r.code;
      counts = r.counts;
      // Field count is irrelevant for template shims — the template owns rendering.
      fieldKeyCount = 0;
    } else if (item.type === 'index_filter') {
      // Don't query Supabase for filters — they reuse parent index content.
      const r = emitIndexFilterStub(item);
      code = r.code;
      counts = r.counts;
      fieldKeyCount = 0;
    } else {
      const fields = await fetchFields(sb, item.key);
      fieldKeyCount = fields.length;
      const r = emitNormalPage(item, fields);
      code = r.code;
      counts = r.counts;
      warnings = r.warnings;
    }

    // Safety: if a file already exists at the target and does NOT start with
    // the GENERATED marker, treat it as hand-edited and skip the write.
    let exists = false;
    try {
      await stat(outAbs);
      exists = true;
    } catch {
      exists = false;
    }
    if (exists) {
      const existing = await readFile(outAbs, 'utf8');
      if (!existing.startsWith(GENERATED_MARKER)) {
        skippedHandEdited.push(outRel);
        warnings.push('skipped: existing file is hand-edited (no GENERATED marker)');
        manifest.push({
          key: item.key,
          type: item.type,
          newPath: item.newPath,
          outFile: outRel,
          fieldKeyCount,
          componentCounts: counts,
          warnings,
        });
        continue;
      }
    }

    await mkdir(dirname(outAbs), { recursive: true });
    await writeFile(outAbs, code, 'utf8');

    manifest.push({
      key: item.key,
      type: item.type,
      newPath: item.newPath,
      outFile: outRel,
      fieldKeyCount,
      componentCounts: counts,
      warnings,
    });

    console.log(`  ✓ ${item.key.padEnd(50)} → ${outRel}  (${fieldKeyCount} fields, ${counts.EditableContent}c/${counts.EditableRichText}r/${counts.EditableImage}i)`);
  }

  // Resolve collision warnings post-hoc
  for (const [outFile, keys] of outFileToKeys) {
    if (keys.length > 1) {
      for (const entry of manifest) {
        if (entry.outFile === outFile) {
          entry.warnings.push(`PATH COLLISION with: ${keys.filter((k) => k !== entry.key).join(', ')}`);
        }
      }
    }
  }

  // Aggregate component counts for summary
  const totals = manifest.reduce(
    (acc, e) => {
      acc.EditableContent += e.componentCounts.EditableContent;
      acc.EditableRichText += e.componentCounts.EditableRichText;
      acc.EditableImage += e.componentCounts.EditableImage;
      return acc;
    },
    { EditableContent: 0, EditableRichText: 0, EditableImage: 0 },
  );

  const allWarnings = manifest.flatMap((e) => e.warnings.map((w) => `${e.key}: ${w}`));

  const manifestDoc = {
    generatedAt: new Date().toISOString(),
    count: manifest.length,
    componentTotals: totals,
    files: manifest,
  };
  await writeFile(MANIFEST_PATH, JSON.stringify(manifestDoc, null, 2) + '\n', 'utf8');

  console.log(`\n═══ MANIFEST SUMMARY ═══\n`);
  console.log(`Total files generated: ${manifest.length}`);
  console.log(`Component totals: EditableContent=${totals.EditableContent}, EditableRichText=${totals.EditableRichText}, EditableImage=${totals.EditableImage}`);
  console.log(`Warnings: ${allWarnings.length}`);
  for (const w of allWarnings) console.log(`  ⚠ ${w}`);

  // Per-page dedupe summary — top 10 pages by collapsed count
  if (dedupeReport.length > 0) {
    dedupeReport.sort((a, b) => b.collapsed - a.collapsed);
    const totalCollapsed = dedupeReport.reduce((n, r) => n + r.collapsed, 0);
    console.log(`\n═══ DEDUPE REPORT ═══`);
    console.log(`Pages with collapsed rows: ${dedupeReport.length} (total rows collapsed: ${totalCollapsed})`);
    const top = dedupeReport.slice(0, 10);
    for (const r of top) {
      console.log(`\n  ${r.pageKey}  (collapsed ${r.collapsed})`);
      for (const d of r.details) {
        console.log(`    KEPT  ${d.kept}  ← "${d.sample}"`);
        for (const lost of d.dropped) console.log(`    LOST  ${lost}`);
      }
    }
    if (dedupeReport.length > 10) {
      console.log(`\n  … and ${dedupeReport.length - 10} more page(s) with collapsed rows`);
    }
  } else {
    console.log(`\nDedupe report: no same-value duplicates found`);
  }

  console.log(`\nManifest written to: ${MANIFEST_PATH}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
