#!/usr/bin/env npx tsx
/**
 * Phase G — Step 2: per-file delete of pages whose line 1 starts with the
 * GENERATED marker. Hand-written files (layout/loading/error/section partials)
 * are preserved. Empty directories under (site)/ are pruned afterwards.
 *
 * NEVER deletes (site)/ itself.
 */

import { readFile, readdir, stat, unlink, rmdir } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const SITE_DIR = resolve(__dirname, '..');
const TARGET_DIR = join(SITE_DIR, 'src/app/(site)');

const MARKER = '// GENERATED by scripts/codegen-pages.ts';

async function* walkTsx(root: string): AsyncGenerator<string> {
  const entries = await readdir(root, { withFileTypes: true });
  for (const e of entries) {
    const full = join(root, e.name);
    if (e.isDirectory()) yield* walkTsx(full);
    else if (e.isFile() && e.name.endsWith('.tsx')) yield full;
  }
}

async function isEmptyDir(dir: string): Promise<boolean> {
  const entries = await readdir(dir);
  return entries.length === 0;
}

async function pruneEmpty(root: string, never: string): Promise<string[]> {
  const pruned: string[] = [];
  // Post-order recurse
  const entries = await readdir(root, { withFileTypes: true });
  for (const e of entries) {
    if (e.isDirectory()) {
      pruned.push(...(await pruneEmpty(join(root, e.name), never)));
    }
  }
  if (root !== never) {
    if (await isEmptyDir(root)) {
      await rmdir(root);
      pruned.push(root);
    }
  }
  return pruned;
}

async function main() {
  const deleted: string[] = [];
  const preserved: string[] = [];

  for await (const file of walkTsx(TARGET_DIR)) {
    const text = await readFile(file, 'utf8');
    const firstLine = text.split('\n', 1)[0] ?? '';
    if (firstLine.startsWith(MARKER)) {
      await unlink(file);
      deleted.push(file);
    } else {
      preserved.push(file);
    }
  }

  const pruned = await pruneEmpty(TARGET_DIR, TARGET_DIR);

  const rel = (p: string) => p.replace(SITE_DIR + '/', '');

  console.log(`\nDeleted (${deleted.length}):`);
  for (const f of deleted) console.log(`  ✗ ${rel(f)}`);

  console.log(`\nPreserved (${preserved.length}):`);
  for (const f of preserved) console.log(`  ◯ ${rel(f)}`);

  console.log(`\nDirectories pruned (${pruned.length}):`);
  for (const d of pruned) console.log(`  ⌫ ${rel(d)}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
