// GENERATED by scripts/codegen-pages.ts — do not hand-edit
import type { Metadata } from "next";
import { fetchPageContent } from "@/lib/content";
import { ContentProviderWrapper } from "@/components/ContentProviderWrapper";
import { EditableContent } from "@/components/EditableContent";
import { EditableRichText } from "@/components/EditableRichText";

const PAGE_KEY = "prayer";

export async function generateMetadata(): Promise<Metadata> {
  const [page, global] = await Promise.all([
    fetchPageContent(PAGE_KEY),
    fetchPageContent("global"),
  ]);
  const title = page.get("meta.title")?.value ?? global.get("meta.title")?.value ?? "";
  const description = page.get("meta.description")?.value ?? global.get("meta.description")?.value ?? "";
  return { title, description };
}

export default async function PrayerPage() {
  const content = await fetchPageContent(PAGE_KEY);
  const contentEntries = Array.from(content.values());
  return (
    <ContentProviderWrapper pageKey={PAGE_KEY} entries={contentEntries}>
      <section data-group="h1">
        <EditableContent fieldKey="h1.01" as="h1" />
      </section>
      <section data-group="p">
        <EditableRichText fieldKey="p.01" />
        <EditableRichText fieldKey="p.02" />
      </section>
      <section data-group="form">
        <EditableContent fieldKey="form.button" as="span" />
        <EditableContent fieldKey="form.error" as="span" />
        <EditableContent fieldKey="form.label.email_optional" as="label" />
        <EditableContent fieldKey="form.label.request" as="label" />
        <EditableContent fieldKey="form.success" as="span" />
      </section>
    </ContentProviderWrapper>
  );
}
