// GENERATED by scripts/codegen-pages.ts — do not hand-edit
import type { Metadata } from "next";
import { fetchPageContent } from "@/lib/content";
import { ContentProviderWrapper } from "@/components/ContentProviderWrapper";
import { EditableRichText } from "@/components/EditableRichText";

const PAGE_KEY = "events.weekly-bible-study-group";

export async function generateMetadata(): Promise<Metadata> {
  const [page, global] = await Promise.all([
    fetchPageContent(PAGE_KEY),
    fetchPageContent("global"),
  ]);
  const title = page.get("meta.title")?.value ?? global.get("meta.title")?.value ?? "";
  const description = page.get("meta.description")?.value ?? global.get("meta.description")?.value ?? "";
  return { title, description };
}

export default async function EventsWeeklyBibleStudyGroupPage() {
  const content = await fetchPageContent(PAGE_KEY);
  const contentEntries = Array.from(content.values());
  return (
    <ContentProviderWrapper pageKey={PAGE_KEY} entries={contentEntries}>
      <section data-group="p">
        <EditableRichText fieldKey="p.01" />
        <EditableRichText fieldKey="p.02" />
        <EditableRichText fieldKey="p.03" />
        <EditableRichText fieldKey="p.04" />
        <EditableRichText fieldKey="p.05" />
      </section>
    </ContentProviderWrapper>
  );
}
