// HAND-AUTHORED — not generated by codegen. /sermons/scripture is a
// derived index page that doesn't exist in route-map.json; the codegen
// won't touch it because there's no GENERATED marker.
import type { Metadata } from "next";
import Link from "next/link";
import { getScriptureIndex } from "@/lib/scriptureIndex";

export const metadata: Metadata = {
  title: "Scripture Index — Yeshua Deliverance Ministries",
  description:
    "Every Bible passage referenced across YDM sermons, organized by book and chapter.",
};

export const dynamic = "force-dynamic";

export default async function ScriptureIndexPage() {
  const groups = await getScriptureIndex();
  const totalRefs = groups.reduce((n, g) => n + g.refs.length, 0);

  return (
    <>
      {/* HERO */}
      <section className="-mx-4 bg-ydm-cream py-16 sm:-mx-6 sm:py-20">
        <div className="mx-auto max-w-5xl px-4 text-center sm:px-6">
          <p className="m-0 mb-3 font-accent text-sm uppercase tracking-[0.3em] text-ydm-gold">
            CROSS-REFERENCE
          </p>
          <p className="m-0 mb-4 font-script text-4xl text-ydm-amber sm:text-5xl">
            Search the Word
          </p>
          <h1 className="m-0 mb-6 font-display text-5xl uppercase leading-none text-ydm-ink sm:text-7xl">
            Scripture Index
          </h1>
          <p className="m-0 font-serif text-lg leading-relaxed text-ydm-text">
            Every passage Bishop Wilson has preached from, organized by book.
            Click any reference to jump to the sermon.
          </p>
          <p className="m-0 mt-4 font-accent text-xs uppercase tracking-wider text-ydm-muted">
            {totalRefs} references across {groups.length} books
          </p>
          <p className="m-0 mt-6">
            <Link
              href="/sermons"
              className="font-accent text-sm uppercase tracking-wider text-ydm-gold no-underline hover:text-ydm-amber"
            >
              ← Back to all sermons
            </Link>
          </p>
        </div>
      </section>

      {/* INDEX */}
      <section className="bg-ydm-surface py-16 sm:py-20">
        <div className="mx-auto max-w-5xl px-4 sm:px-6">
          {groups.length === 0 ? (
            <p className="m-0 text-center font-serif text-lg text-ydm-muted">
              No scripture references yet — check back as more sermons are
              published.
            </p>
          ) : (
            <>
              {/* Book jump-nav */}
              <nav className="mb-12 rounded-sm border border-ydm-line bg-ydm-cream/40 p-5">
                <p className="m-0 mb-3 font-accent text-xs uppercase tracking-wider text-ydm-muted">
                  Jump to book
                </p>
                <ul className="m-0 flex flex-wrap gap-x-4 gap-y-1 p-0 list-none">
                  {groups.map((g) => (
                    <li key={g.book}>
                      <a
                        href={`#${slugifyBook(g.book)}`}
                        className="font-display text-sm uppercase tracking-wide text-ydm-ink no-underline hover:text-ydm-gold"
                      >
                        {g.book}
                        <span className="ml-1 font-accent text-[10px] text-ydm-muted">
                          ({g.refs.length})
                        </span>
                      </a>
                    </li>
                  ))}
                </ul>
              </nav>

              {/* Per-book sections */}
              <div className="space-y-12">
                {groups.map((g) => (
                  <section
                    key={g.book}
                    id={slugifyBook(g.book)}
                    className="scroll-mt-24"
                  >
                    <h2 className="m-0 mb-4 border-b border-ydm-line pb-2 font-display text-3xl uppercase tracking-wide text-ydm-ink">
                      {g.book}
                    </h2>
                    <ul className="m-0 space-y-4 p-0 list-none">
                      {g.refs.map((entry) => (
                        <li
                          key={entry.ref}
                          className="rounded-sm border border-ydm-line/60 bg-ydm-cream/20 p-4"
                        >
                          <p className="m-0 mb-2 font-display text-lg text-ydm-ink">
                            {entry.ref}
                          </p>
                          {entry.text ? (
                            <blockquote className="m-0 mb-3 border-l-2 border-ydm-gold pl-4 font-serif text-sm leading-relaxed text-ydm-text">
                              <p className="m-0 whitespace-pre-wrap">
                                {entry.text.length > 280
                                  ? entry.text.slice(0, 280).trimEnd() + "…"
                                  : entry.text}
                              </p>
                              {entry.translation ? (
                                <cite className="not-italic mt-2 block font-accent text-[10px] uppercase tracking-wider text-ydm-muted">
                                  {entry.translation}
                                </cite>
                              ) : null}
                            </blockquote>
                          ) : null}
                          <p className="m-0 font-accent text-xs uppercase tracking-wider text-ydm-muted">
                            Preached in:
                          </p>
                          <ul className="m-0 mt-1 space-y-1 p-0 list-none">
                            {entry.sermons.map((s) => (
                              <li key={s.slug}>
                                <Link
                                  href={`/sermons/${s.slug}`}
                                  className="font-serif text-sm text-ydm-ink no-underline hover:text-ydm-gold"
                                >
                                  → {s.title}
                                </Link>
                              </li>
                            ))}
                          </ul>
                        </li>
                      ))}
                    </ul>
                  </section>
                ))}
              </div>
            </>
          )}
        </div>
      </section>
    </>
  );
}

function slugifyBook(book: string): string {
  return book.toLowerCase().replace(/\s+/g, "-");
}
