// GENERATED by scripts/codegen-pages.ts — do not hand-edit unless you also update codegen
import type { Metadata } from "next";
import { fetchPageContent, fetchAssets } from "@/lib/content";
import { ContentProviderWrapper } from "@/components/ContentProviderWrapper";
import { AssetProviderWrapper } from "@/components/AssetProviderWrapper";

const PAGE_KEY = "singleton.ask";

export async function generateMetadata(): Promise<Metadata> {
  const [page, global] = await Promise.all([
    fetchPageContent(PAGE_KEY),
    fetchPageContent("global"),
  ]);
  const siteName = global.get("site_name")?.value ?? "Yeshua Deliverance Ministries";
  const title = page.get("seo.title")?.value ?? global.get("seo.title")?.value ?? "";
  const description = page.get("seo.description")?.value ?? global.get("seo.description")?.value ?? "";
  return {
    title,
    description,
    openGraph: { title, description, siteName },
  };
}

export default async function SingletonAskPage() {
  const [content, assets] = await Promise.all([
    fetchPageContent(PAGE_KEY),
    fetchAssets(PAGE_KEY + "."),
  ]);
  const contentEntries = Array.from(content.values());
  const assetEntries = Array.from(assets.values());

  return (
    <ContentProviderWrapper pageKey={PAGE_KEY} entries={contentEntries}>
      <AssetProviderWrapper entries={assetEntries}>
        {/* No renderable fields — SEO-only page. Add content rows to page_content to populate. */}
        <section />
      </AssetProviderWrapper>
    </ContentProviderWrapper>
  );
}
