// GENERATED by scripts/codegen-pages.ts — do not hand-edit unless you also update codegen
import type { Metadata } from "next";
import { fetchPageContent, fetchAssets } from "@/lib/content";
import { ContentProviderWrapper } from "@/components/ContentProviderWrapper";
import { AssetProviderWrapper } from "@/components/AssetProviderWrapper";
import { EditableContent } from "@/components/EditableContent";
import { EditableRichText } from "@/components/EditableRichText";

const PAGE_KEY = "contact";

export async function generateMetadata(): Promise<Metadata> {
  const [page, global] = await Promise.all([
    fetchPageContent(PAGE_KEY),
    fetchPageContent("global"),
  ]);
  const siteName = global.get("site_name")?.value ?? "Yeshua Deliverance Ministries";
  const title = page.get("seo.title")?.value ?? global.get("seo.title")?.value ?? "";
  const description = page.get("seo.description")?.value ?? global.get("seo.description")?.value ?? "";
  return {
    title,
    description,
    openGraph: { title, description, siteName },
  };
}

export default async function ContactPage() {
  const [content, assets] = await Promise.all([
    fetchPageContent(PAGE_KEY),
    fetchAssets(PAGE_KEY + "."),
  ]);
  const contentEntries = Array.from(content.values());
  const assetEntries = Array.from(assets.values());

  return (
    <ContentProviderWrapper pageKey={PAGE_KEY} entries={contentEntries}>
      <AssetProviderWrapper entries={assetEntries}>
        {/* section: hero */}
        <section>
          <EditableContent fieldKey="hero.title" as="h2" />
          <EditableContent fieldKey="hero.subtitle" as="p" />
        </section>
        {/* section: info */}
        <section>
          <EditableContent fieldKey="info.title" as="h2" />
          <EditableRichText fieldKey="info.body" />
          <EditableContent fieldKey="info.phone_label" as="p" />
          <EditableContent fieldKey="info.email_label" as="p" />
          <EditableContent fieldKey="info.address_label" as="p" />
          <EditableContent fieldKey="info.venue_label" as="p" />
        </section>
        {/* section: hours */}
        <section>
          <EditableContent fieldKey="hours.title" as="h2" />
          <EditableContent fieldKey="hours.sunday_note" as="p" />
          <EditableContent fieldKey="hours.biblestudy_note" as="p" />
        </section>
        {/* section: form */}
        <section>
          {/* TODO: EditableList not yet implemented — 9 repeating items under "form.category" */}
          <EditableContent fieldKey="form.category.1.label" as="p" />
          <EditableContent fieldKey="form.category.2.label" as="p" />
          <EditableContent fieldKey="form.category.3.label" as="p" />
          <EditableContent fieldKey="form.category.4.label" as="p" />
          <EditableContent fieldKey="form.category.5.label" as="p" />
          <EditableContent fieldKey="form.category.6.label" as="p" />
          <EditableContent fieldKey="form.category.7.label" as="p" />
          <EditableContent fieldKey="form.category.8.label" as="p" />
          <EditableContent fieldKey="form.category.9.label" as="p" />
          <EditableContent fieldKey="form.title" as="h2" />
          <EditableRichText fieldKey="form.intro" />
          <EditableContent fieldKey="form.field.name_label" as="p" />
          <EditableContent fieldKey="form.field.email_label" as="p" />
          <EditableContent fieldKey="form.field.phone_label" as="p" />
          <EditableContent fieldKey="form.field.org_label" as="p" />
          <EditableContent fieldKey="form.field.category_label" as="p" />
          <EditableContent fieldKey="form.field.message_label" as="p" />
          <EditableContent fieldKey="form.field.consent_label" as="p" />
          <EditableContent fieldKey="form.submit.label" as="p" />
          <EditableContent fieldKey="form.success.title" as="h2" />
          <EditableRichText fieldKey="form.success.body" />
        </section>
        {/* section: map */}
        <section>
          <EditableContent fieldKey="map.title" as="h2" />
          <EditableContent fieldKey="map.embed_lat" as="span" /> {/* TODO: format number */}
          <EditableContent fieldKey="map.embed_lng" as="span" /> {/* TODO: format number */}
          <EditableContent fieldKey="map.caption" as="p" />
        </section>
      </AssetProviderWrapper>
    </ContentProviderWrapper>
  );
}
