// GENERATED by scripts/codegen-pages.ts — do not hand-edit
import type { Metadata } from "next";
import { fetchPageContent, fetchAssets } from "@/lib/content";
import { ContentProviderWrapper } from "@/components/ContentProviderWrapper";
import { AssetProviderWrapper } from "@/components/AssetProviderWrapper";
import { ContactTemplate } from "@/components/templates/ContactTemplate";

const PAGE_KEY = "contact";

export async function generateMetadata(): Promise<Metadata> {
  const [page, global] = await Promise.all([
    fetchPageContent(PAGE_KEY),
    fetchPageContent("global"),
  ]);
  const title = page.get("meta.title")?.value ?? global.get("meta.title")?.value ?? "";
  const description = page.get("meta.description")?.value ?? global.get("meta.description")?.value ?? "";
  return { title, description };
}

export default async function ContactPage() {
  const [content, assets] = await Promise.all([
    fetchPageContent(PAGE_KEY),
    fetchAssets(PAGE_KEY + "."),
  ]);
  const contentEntries = Array.from(content.values());
  const assetEntries = Array.from(assets.values());
  return (
    <ContentProviderWrapper pageKey={PAGE_KEY} entries={contentEntries}>
      <AssetProviderWrapper entries={assetEntries}>
        <ContactTemplate pageKey={PAGE_KEY} />
      </AssetProviderWrapper>
    </ContentProviderWrapper>
  );
}
