// GENERATED by scripts/codegen-pages.ts — do not hand-edit
import type { Metadata } from "next";
import { fetchPageContent, fetchAssets } from "@/lib/content";
import { ContentProviderWrapper } from "@/components/ContentProviderWrapper";
import { AssetProviderWrapper } from "@/components/AssetProviderWrapper";
import { EditableContent } from "@/components/EditableContent";
import { EditableImage } from "@/components/EditableImage";

const PAGE_KEY = "blog.index";

export async function generateMetadata(): Promise<Metadata> {
  const [page, global] = await Promise.all([
    fetchPageContent(PAGE_KEY),
    fetchPageContent("global"),
  ]);
  const title = page.get("meta.title")?.value ?? global.get("meta.title")?.value ?? "";
  const description = page.get("meta.description")?.value ?? global.get("meta.description")?.value ?? "";
  return { title, description };
}

export default async function BlogIndexPage() {
  const [content, assets] = await Promise.all([
    fetchPageContent(PAGE_KEY),
    fetchAssets(PAGE_KEY + "."),
  ]);
  const contentEntries = Array.from(content.values());
  const assetEntries = Array.from(assets.values());
  return (
    <ContentProviderWrapper pageKey={PAGE_KEY} entries={contentEntries}>
      <AssetProviderWrapper entries={assetEntries}>
        <section data-group="h1">
          <EditableContent fieldKey="h1.01" as="h1" />
        </section>
        <section data-group="h3">
          <EditableContent fieldKey="h3.01" as="h3" />
          <EditableContent fieldKey="h3.02" as="h3" />
          <EditableContent fieldKey="h3.03" as="h3" />
          <EditableContent fieldKey="h3.04" as="h3" />
          <EditableContent fieldKey="h3.05" as="h3" />
          <EditableContent fieldKey="h3.06" as="h3" />
          <EditableContent fieldKey="h3.07" as="h3" />
          <EditableContent fieldKey="h3.08" as="h3" />
          <EditableContent fieldKey="h3.09" as="h3" />
        </section>
        <section data-group="image">
          <EditableImage fieldKey="image.01" />
          <EditableImage fieldKey="image.02" />
          <EditableImage fieldKey="image.03" />
          <EditableImage fieldKey="image.04" />
          <EditableImage fieldKey="image.05" />
          <EditableImage fieldKey="image.06" />
          <EditableImage fieldKey="image.07" />
          <EditableImage fieldKey="image.08" />
          <EditableImage fieldKey="image.09" />
        </section>
        <section data-group="list-placeholder">
          {/* TODO Phase H: <ListSection /> for child query */}
        </section>
      </AssetProviderWrapper>
    </ContentProviderWrapper>
  );
}
