// GENERATED by scripts/codegen-pages.ts — do not hand-edit unless you also update codegen
import type { Metadata } from "next";
import { fetchPageContent, fetchAssets } from "@/lib/content";
import { ContentProviderWrapper } from "@/components/ContentProviderWrapper";
import { AssetProviderWrapper } from "@/components/AssetProviderWrapper";
import { EditableContent } from "@/components/EditableContent";
import { EditableRichText } from "@/components/EditableRichText";

const PAGE_KEY = "blog_page";

export async function generateMetadata(): Promise<Metadata> {
  const [page, global] = await Promise.all([
    fetchPageContent(PAGE_KEY),
    fetchPageContent("global"),
  ]);
  const siteName = global.get("site_name")?.value ?? "Yeshua Deliverance Ministries";
  const title = page.get("seo.title")?.value ?? global.get("seo.title")?.value ?? "";
  const description = page.get("seo.description")?.value ?? global.get("seo.description")?.value ?? "";
  return {
    title,
    description,
    openGraph: { title, description, siteName },
  };
}

export default async function BlogPagePage() {
  const [content, assets] = await Promise.all([
    fetchPageContent(PAGE_KEY),
    fetchAssets(PAGE_KEY + "."),
  ]);
  const contentEntries = Array.from(content.values());
  const assetEntries = Array.from(assets.values());

  return (
    <ContentProviderWrapper pageKey={PAGE_KEY} entries={contentEntries}>
      <AssetProviderWrapper entries={assetEntries}>
        {/* section: hero */}
        <section>
          <EditableContent fieldKey="hero.title" as="h2" />
          <EditableContent fieldKey="hero.subtitle" as="p" />
        </section>
        {/* section: intro */}
        <section>
          <EditableRichText fieldKey="intro.body" />
        </section>
        {/* section: list */}
        <section>
          <EditableContent fieldKey="list.empty_state" as="p" />
          <EditableContent fieldKey="list.filter_all.label" as="p" />
          <EditableContent fieldKey="list.filter_faith.label" as="p" />
          <EditableContent fieldKey="list.filter_word.label" as="p" />
          <EditableContent fieldKey="list.filter_jesus.label" as="p" />
          <EditableContent fieldKey="list.search.placeholder" as="p" />
        </section>
      </AssetProviderWrapper>
    </ContentProviderWrapper>
  );
}
