// GENERATED by scripts/codegen-pages.ts — do not hand-edit
import type { Metadata } from "next";
import { fetchPageContent, fetchAssets } from "@/lib/content";
import { ContentProviderWrapper } from "@/components/ContentProviderWrapper";
import { AssetProviderWrapper } from "@/components/AssetProviderWrapper";
import { EditableContent } from "@/components/EditableContent";
import { EditableRichText } from "@/components/EditableRichText";
import { EditableImage } from "@/components/EditableImage";

const PAGE_KEY = "blog.how-do-i-intercede-for-family-who-dont-believe-in-jesus";

export async function generateMetadata(): Promise<Metadata> {
  const [page, global] = await Promise.all([
    fetchPageContent(PAGE_KEY),
    fetchPageContent("global"),
  ]);
  const title = page.get("meta.title")?.value ?? global.get("meta.title")?.value ?? "";
  const description = page.get("meta.description")?.value ?? global.get("meta.description")?.value ?? "";
  return { title, description };
}

export default async function BlogHowDoIIntercedeForFamilyWhoDontBelieveInJesusPage() {
  const [content, assets] = await Promise.all([
    fetchPageContent(PAGE_KEY),
    fetchAssets(PAGE_KEY + "."),
  ]);
  const contentEntries = Array.from(content.values());
  const assetEntries = Array.from(assets.values());
  return (
    <ContentProviderWrapper pageKey={PAGE_KEY} entries={contentEntries}>
      <AssetProviderWrapper entries={assetEntries}>
        <section data-group="h3">
          <EditableContent fieldKey="h3.01" as="h3" />
          <EditableContent fieldKey="h3.02" as="h3" />
          <EditableContent fieldKey="h3.03" as="h3" />
        </section>
        <section data-group="p">
          <EditableRichText fieldKey="p.01" />
          <EditableRichText fieldKey="p.02" />
          <EditableRichText fieldKey="p.03" />
          <EditableRichText fieldKey="p.04" />
          <EditableRichText fieldKey="p.05" />
          <EditableRichText fieldKey="p.06" />
          <EditableRichText fieldKey="p.07" />
          <EditableRichText fieldKey="p.08" />
          <EditableRichText fieldKey="p.09" />
          <EditableRichText fieldKey="p.10" />
        </section>
        <section data-group="list">
          <EditableRichText fieldKey="list.01" />
          <EditableRichText fieldKey="list.02" />
        </section>
        <section data-group="image">
          <EditableImage fieldKey="image.01" />
        </section>
      </AssetProviderWrapper>
    </ContentProviderWrapper>
  );
}
