// GENERATED by scripts/codegen-pages.ts — do not hand-edit
import type { Metadata } from "next";
import { fetchPageContent } from "@/lib/content";
import { ContentProviderWrapper } from "@/components/ContentProviderWrapper";
import { EditableContent } from "@/components/EditableContent";
import { EditableRichText } from "@/components/EditableRichText";

const PAGE_KEY = "about";

export async function generateMetadata(): Promise<Metadata> {
  const [page, global] = await Promise.all([
    fetchPageContent(PAGE_KEY),
    fetchPageContent("global"),
  ]);
  const title = page.get("meta.title")?.value ?? global.get("meta.title")?.value ?? "";
  const description = page.get("meta.description")?.value ?? global.get("meta.description")?.value ?? "";
  return { title, description };
}

export default async function AboutPage() {
  const content = await fetchPageContent(PAGE_KEY);
  const contentEntries = Array.from(content.values());
  return (
    <ContentProviderWrapper pageKey={PAGE_KEY} entries={contentEntries}>
      <section data-group="h2">
        <EditableContent fieldKey="h2.01" as="h2" />
        <EditableContent fieldKey="h2.02" as="h2" />
        <EditableContent fieldKey="h2.03" as="h2" />
        <EditableContent fieldKey="h2.04" as="h2" />
      </section>
      <section data-group="h3">
        <EditableContent fieldKey="h3.01" as="h3" />
      </section>
      <section data-group="p">
        <EditableRichText fieldKey="p.01" />
        <EditableRichText fieldKey="p.02" />
        <EditableRichText fieldKey="p.03" />
        <EditableRichText fieldKey="p.04" />
        <EditableRichText fieldKey="p.05" />
        <EditableRichText fieldKey="p.06" />
        <EditableRichText fieldKey="p.07" />
        <EditableRichText fieldKey="p.08" />
        <EditableRichText fieldKey="p.09" />
        <EditableRichText fieldKey="p.10" />
        <EditableRichText fieldKey="p.11" />
      </section>
      <section data-group="other">
        <EditableRichText fieldKey="beliefs.intro" />
        <EditableRichText fieldKey="beliefs.item1.body" />
        <EditableContent fieldKey="beliefs.item1.title" as="span" />
        <EditableRichText fieldKey="beliefs.item2.body" />
        <EditableContent fieldKey="beliefs.item2.title" as="span" />
        <EditableRichText fieldKey="beliefs.item3.body" />
        <EditableContent fieldKey="beliefs.item3.title" as="span" />
        <EditableRichText fieldKey="beliefs.item4.body" />
        <EditableContent fieldKey="beliefs.item4.title" as="span" />
        <EditableRichText fieldKey="beliefs.item5.body" />
        <EditableContent fieldKey="beliefs.item5.title" as="span" />
        <EditableContent fieldKey="beliefs.title" as="span" />
        <EditableRichText fieldKey="cta.body" />
        <EditableContent fieldKey="cta.primary.href" as="span" />
        <EditableContent fieldKey="cta.primary.label" as="span" />
        <EditableContent fieldKey="cta.secondary.href" as="span" />
        <EditableContent fieldKey="cta.secondary.label" as="span" />
        <EditableContent fieldKey="cta.title" as="span" />
        <EditableContent fieldKey="hero.bg_image" as="span" />
        <EditableContent fieldKey="hero.subtitle" as="span" />
        <EditableContent fieldKey="hero.title" as="span" />
        <EditableRichText fieldKey="leadership_teaser.body" />
        <EditableContent fieldKey="leadership_teaser.cta.href" as="span" />
        <EditableContent fieldKey="leadership_teaser.cta.label" as="span" />
        <EditableContent fieldKey="leadership_teaser.title" as="span" />
        <EditableRichText fieldKey="story.body" />
        <EditableContent fieldKey="story.eyebrow" as="span" />
        <EditableContent fieldKey="story.title" as="span" />
      </section>
    </ContentProviderWrapper>
  );
}
