// GENERATED by scripts/codegen-pages.ts — do not hand-edit unless you also update codegen
import type { Metadata } from "next";
import { fetchPageContent, fetchAssets } from "@/lib/content";
import { ContentProviderWrapper } from "@/components/ContentProviderWrapper";
import { AssetProviderWrapper } from "@/components/AssetProviderWrapper";
import { EditableContent } from "@/components/EditableContent";
import { EditableRichText } from "@/components/EditableRichText";
import { EditableImage } from "@/components/EditableImage";
import { EditableLink } from "@/components/EditableLink";
import { ContentBlockList } from "@/components/ListSection";

const PAGE_KEY = "about";

export async function generateMetadata(): Promise<Metadata> {
  const [page, global] = await Promise.all([
    fetchPageContent(PAGE_KEY),
    fetchPageContent("global"),
  ]);
  const siteName = global.get("site_name")?.value ?? "Yeshua Deliverance Ministries";
  const title = page.get("seo.title")?.value ?? global.get("seo.title")?.value ?? "";
  const description = page.get("seo.description")?.value ?? global.get("seo.description")?.value ?? "";
  return {
    title,
    description,
    openGraph: { title, description, siteName },
  };
}

export default async function AboutPage() {
  const [content, assets] = await Promise.all([
    fetchPageContent(PAGE_KEY),
    fetchAssets(PAGE_KEY + "."),
  ]);
  const contentEntries = Array.from(content.values());
  const assetEntries = Array.from(assets.values());

  return (
    <ContentProviderWrapper pageKey={PAGE_KEY} entries={contentEntries}>
      <AssetProviderWrapper entries={assetEntries}>
        {/* section: hero */}
        <section>
          <EditableContent fieldKey="hero.title" as="h2" />
          <EditableContent fieldKey="hero.subtitle" as="p" />
          <EditableImage fieldKey="hero.bg_image" />
        </section>
        {/* section: story */}
        <section>
          <EditableContent fieldKey="story.eyebrow" as="p" />
          <EditableContent fieldKey="story.title" as="h2" />
          <EditableRichText fieldKey="story.body" />
        </section>
        {/* section: beliefs */}
        <section>
          {/* validate:list-prefix="beliefs" */}
          <ContentBlockList itemPrefix="beliefs" subKeys={[{ key: "title", as: "h3", type: "text" as const }, { key: "body", as: "p", type: "richtext" as const }]} />
          <EditableContent fieldKey="beliefs.title" as="h2" />
          <EditableRichText fieldKey="beliefs.intro" />
        </section>
        {/* section: leadership_teaser */}
        <section>
          <EditableContent fieldKey="leadership_teaser.title" as="h2" />
          <EditableRichText fieldKey="leadership_teaser.body" />
          <EditableLink fieldKey="leadership_teaser.cta" />
        </section>
        {/* section: cta */}
        <section>
          <EditableContent fieldKey="cta.title" as="h2" />
          <EditableRichText fieldKey="cta.body" />
          <EditableLink fieldKey="cta.primary" />
          <EditableLink fieldKey="cta.secondary" />
        </section>
      </AssetProviderWrapper>
    </ContentProviderWrapper>
  );
}
