// GENERATED by scripts/codegen-pages.ts — do not hand-edit unless you also update codegen
import type { Metadata } from "next";
import { fetchPageContent, fetchAssets } from "@/lib/content";
import { ContentProviderWrapper } from "@/components/ContentProviderWrapper";
import { AssetProviderWrapper } from "@/components/AssetProviderWrapper";
import { EditableContent } from "@/components/EditableContent";
import { EditableRichText } from "@/components/EditableRichText";
import { LinkList } from "@/components/ListSection";

const PAGE_KEY = "sermon.whats_your_view_of_marriage";

export async function generateMetadata(): Promise<Metadata> {
  const [page, global] = await Promise.all([
    fetchPageContent(PAGE_KEY),
    fetchPageContent("global"),
  ]);
  const siteName = global.get("site_name")?.value ?? "Yeshua Deliverance Ministries";
  const title = page.get("seo.title")?.value ?? global.get("seo.title")?.value ?? "";
  const description = page.get("seo.description")?.value ?? global.get("seo.description")?.value ?? "";
  return {
    title,
    description,
    openGraph: { title, description, siteName },
  };
}

export default async function SermonWhatsYourViewOfMarriagePage() {
  const [content, assets] = await Promise.all([
    fetchPageContent(PAGE_KEY),
    fetchAssets(PAGE_KEY + "."),
  ]);
  const contentEntries = Array.from(content.values());
  const assetEntries = Array.from(assets.values());

  return (
    <ContentProviderWrapper pageKey={PAGE_KEY} entries={contentEntries}>
      <AssetProviderWrapper entries={assetEntries}>
        {/* section: hero */}
        <section>
          <EditableContent fieldKey="hero.title" as="h2" />
        </section>
        {/* section: body */}
        <section>
          <EditableRichText fieldKey="body.p1" />
          <EditableRichText fieldKey="body.p2" />
          <EditableRichText fieldKey="body.p3" />
          <EditableRichText fieldKey="body.p4" />
          <EditableRichText fieldKey="body.p5" />
          <EditableRichText fieldKey="body.p6" />
          <EditableRichText fieldKey="body.p7" />
        </section>
        {/* section: sections */}
        <section>
          <EditableContent fieldKey="sections.h3_1" as="p" />
          <EditableContent fieldKey="sections.h3_2" as="p" />
          <EditableContent fieldKey="sections.h3_3" as="p" />
          <EditableContent fieldKey="sections.h3_4" as="p" />
          <EditableContent fieldKey="sections.h3_5" as="p" />
          <EditableContent fieldKey="sections.h3_6" as="p" />
        </section>
        {/* section: cta */}
        <section>
          {/* validate:list-prefix="cta" */}
          <LinkList itemPrefix="cta" />
        </section>
      </AssetProviderWrapper>
    </ContentProviderWrapper>
  );
}
