// GENERATED by scripts/codegen-pages.ts — do not hand-edit
import type { Metadata } from "next";
import { fetchPageContent } from "@/lib/content";
import { ContentProviderWrapper } from "@/components/ContentProviderWrapper";
import { EditableContent } from "@/components/EditableContent";
import { EditableRichText } from "@/components/EditableRichText";

const PAGE_KEY = "blog.your-mission-should-you-choose-to-accept-it";

export async function generateMetadata(): Promise<Metadata> {
  const [page, global] = await Promise.all([
    fetchPageContent(PAGE_KEY),
    fetchPageContent("global"),
  ]);
  const title = page.get("meta.title")?.value ?? global.get("meta.title")?.value ?? "";
  const description = page.get("meta.description")?.value ?? global.get("meta.description")?.value ?? "";
  return { title, description };
}

export default async function BlogYourMissionShouldYouChooseToAcceptItPage() {
  const content = await fetchPageContent(PAGE_KEY);
  const contentEntries = Array.from(content.values());
  return (
    <ContentProviderWrapper pageKey={PAGE_KEY} entries={contentEntries}>
      <section data-group="h3">
        <EditableContent fieldKey="h3.01" as="h3" />
        <EditableContent fieldKey="h3.02" as="h3" />
        <EditableContent fieldKey="h3.03" as="h3" />
        <EditableContent fieldKey="h3.04" as="h3" />
      </section>
      <section data-group="p">
        <EditableRichText fieldKey="p.01" />
        <EditableRichText fieldKey="p.02" />
        <EditableRichText fieldKey="p.03" />
        <EditableRichText fieldKey="p.04" />
        <EditableRichText fieldKey="p.05" />
        <EditableRichText fieldKey="p.06" />
        <EditableRichText fieldKey="p.07" />
        <EditableRichText fieldKey="p.08" />
      </section>
    </ContentProviderWrapper>
  );
}
