#!/usr/bin/env python3
"""
generate_seed_sql.py  —  Emit SQL INSERT statements for page_content from content-map.json.

Walks the merged content-map.json tree, derives (page_key, field_key) from each leaf's path,
and produces an idempotent upsert script Mikey can paste into Supabase SQL Editor.

Path derivation:
  home.hero.title                         →  page_key="home",             field_key="hero.title"
  ministry.family.hero.title              →  page_key="ministry.family",  field_key="hero.title"
  sermon.<slug>.body.p3                   →  page_key="sermon.<slug>",    field_key="body.p3"

Leaf shape: a dict containing 'type' and either 'value' or '__needs_authoring__'.
If __needs_authoring__ is true, seed the row with empty string (CMS picks it up for authoring).

Run:
  python3 generate_seed_sql.py
Output:
  archive/wordpress/scrape/seed-page-content.sql
"""
from __future__ import annotations
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
SCRAPE_ROOT = HERE.parent
CONTENT_MAP = SCRAPE_ROOT / "content-map.json"
OUT_SQL = SCRAPE_ROOT / "seed-page-content.sql"

def escape(s: str) -> str:
    """SQL string escape — double single-quotes."""
    return s.replace("'", "''")

def walk_leaves(node, path=()):
    """Yield (path_tuple, leaf_dict) for every leaf in the content-map."""
    if isinstance(node, dict):
        if "type" in node and ("value" in node or "__needs_authoring__" in node):
            yield path, node
        else:
            for k, v in node.items():
                yield from walk_leaves(v, path + (k,))

def main():
    if not CONTENT_MAP.exists():
        print(f"Missing {CONTENT_MAP}", file=sys.stderr)
        sys.exit(1)

    with CONTENT_MAP.open() as f:
        cm = json.load(f)

    rows: list[tuple[str, str, str, str, bool]] = []  # (page_key, field_key, value, value_type, needs_authoring)

    # Skip _meta
    for k, v in cm.items():
        if k == "_meta":
            continue
        for path, leaf in walk_leaves(v, (k,)):
            if len(path) < 2:
                continue  # shouldn't happen, but defensive
            page_key = ".".join(path[:-1])
            field_key = path[-1]
            value_type = leaf.get("type", "text")
            raw = leaf.get("value")
            needs_authoring = bool(leaf.get("__needs_authoring__"))
            if raw is None:
                value = ""
            else:
                value = str(raw)
            rows.append((page_key, field_key, value, value_type, needs_authoring))

    # Sort for diff-friendliness
    rows.sort(key=lambda r: (r[0], r[1]))

    # Emit SQL
    lines: list[str] = []
    lines.append("-- seed-page-content.sql")
    lines.append("-- Generated by scripts/generate_seed_sql.py from content-map.json")
    lines.append(f"-- Rows: {len(rows)}")
    lines.append("-- Idempotent: re-running overwrites values but preserves draft_value + published_at.")
    lines.append("")
    lines.append("begin;")
    lines.append("")

    chunk_size = 500  # one INSERT per 500 rows to keep the SQL editor happy
    for i in range(0, len(rows), chunk_size):
        chunk = rows[i:i + chunk_size]
        lines.append("insert into public.page_content (page_key, field_key, value, value_type) values")
        value_lines = []
        for page_key, field_key, value, value_type, _ in chunk:
            value_lines.append(
                f"  ('{escape(page_key)}', '{escape(field_key)}', '{escape(value)}', '{escape(value_type)}')"
            )
        lines.append(",\n".join(value_lines))
        lines.append("on conflict (page_key, field_key) do update set")
        lines.append("  value = excluded.value,")
        lines.append("  value_type = excluded.value_type,")
        lines.append("  updated_at = now();")
        lines.append("")

    lines.append("commit;")
    lines.append("")
    lines.append(f"-- Done: {len(rows)} page_content rows upserted.")

    OUT_SQL.write_text("\n".join(lines))
    print(f"Wrote {OUT_SQL} ({OUT_SQL.stat().st_size:,} bytes, {len(rows)} rows)")

    # Summary by page_key prefix
    from collections import Counter
    prefix_count = Counter()
    for page_key, *_ in rows:
        first = page_key.split(".")[0]
        prefix_count[first] += 1
    print("\n=== Rows by namespace ===")
    for k in sorted(prefix_count):
        print(f"  {k:20} {prefix_count[k]:>5}")
    print(f"  {'TOTAL':20} {len(rows):>5}")

    # Flag authoring-needed rows
    authoring = [r for r in rows if r[4]]
    print(f"\n__needs_authoring__ rows: {len(authoring)} (seeded as empty strings; Bishop fills in CMS)")

if __name__ == "__main__":
    main()
