// HAND-AUTHORED — not generated by codegen. /testimonials is a curated
// module that replaces the legacy guestbook flow.
import type { Metadata } from "next";
import { TestimonialsTemplate } from "@/components/templates/TestimonialsTemplate";

export const metadata: Metadata = {
  title: "Testimonies — Yeshua Deliverance Ministries",
  description:
    "Stories from members and visitors of how God has moved in their lives through YDM.",
};

export const dynamic = "force-dynamic";

export default async function TestimonialsPage() {
  return <TestimonialsTemplate />;
}
